apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: etclustAC
  region: us-east-1
  version: "1.29"

iam:
  serviceRoleARN: arn:aws:iam::579651781863:role/LabRole

managedNodeGroups:
  - name: nodegroup-etclustAC
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    iam:
      instanceRoleARN: arn:aws:iam::579651781863:role/LabRole
