services:
  database:
    image: mysql:8.0
    container_name: tienda-tech-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tiendatech
    ports:
      - "3306:3306"
    volumes:
      - ./tienda-tech-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - tienda-net

  backend:
    build: ./tienda-tech-backend
    container_name: tienda-tech-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: tiendatech
      DB_PORT: "3306"
    depends_on:
      - database
    networks:
      - tienda-net

  frontend:
    build: ./tienda-tech-frontend
    container_name: tienda-tech-frontend
    ports:
      - "80:80"
    volumes:
      - ./tienda-tech-frontend/index.html:/usr/share/nginx/html/index.html
      - ./tienda-tech-frontend/app.js:/usr/share/nginx/html/app.js
      - ./tienda-tech-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - tienda-net

volumes:
  db_data:

networks:
  tienda-net:
    driver: bridge
